//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellurian.Trains.Protocols.XpressNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tellurian.Trains.Protocols.XpressNet.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid XpressNet speed code..
        /// </summary>
        internal static string CodeIsInvalidSpeedCode {
            get {
                return ResourceManager.GetString("CodeIsInvalidSpeedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XpressNet data has incorrect length..
        /// </summary>
        internal static string DataHasIncorrectLength {
            get {
                return ResourceManager.GetString("DataHasIncorrectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XpressNet data length exceeded..
        /// </summary>
        internal static string DataLengthExceeded {
            get {
                return ResourceManager.GetString("DataLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XpressNet data has invalid header..
        /// </summary>
        internal static string InvalidHeader {
            get {
                return ResourceManager.GetString("InvalidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is RailCom® enabled?.
        /// </summary>
        internal static string IsRailComEnabled {
            get {
                return ResourceManager.GetString("IsRailComEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid number och speed steps..
        /// </summary>
        internal static string NumberIsInvalidNumberOfSpeedSteps {
            get {
                return ResourceManager.GetString("NumberIsInvalidNumberOfSpeedSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main={0}mA/{1}mV, Programming={2}mA, Temp={3}ºC.
        /// </summary>
        internal static string SystemStateFormat {
            get {
                return ResourceManager.GetString("SystemStateFormat", resourceCulture);
            }
        }
    }
}
