//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tellurian.Trains.Protocols.LocoNet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tellurian.Trains.Protocols.LocoNet.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted..
        /// </summary>
        internal static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIFO is full.
        /// </summary>
        internal static string FifoIsFull {
            get {
                return ResourceManager.GetString("FifoIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal move.
        /// </summary>
        internal static string IllegalMove {
            get {
                return ResourceManager.GetString("IllegalMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocoNet: Invalid checksum &apos;{0}&apos; in message {1}..
        /// </summary>
        internal static string InvalidCheckSum {
            get {
                return ResourceManager.GetString("InvalidCheckSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot notification &apos;{0}&apos;.
        /// </summary>
        internal static string SlotNotification {
            get {
                return ResourceManager.GetString("SlotNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undecided.
        /// </summary>
        internal static string Undecided {
            get {
                return ResourceManager.GetString("Undecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocoNet: Unexpected operation code &apos;{0}&apos; in message {1}..
        /// </summary>
        internal static string UnexpectedOperationCode {
            get {
                return ResourceManager.GetString("UnexpectedOperationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocoNet: Unsupported notification &apos;{0}&apos;.
        /// </summary>
        internal static string UnsupportedNotification {
            get {
                return ResourceManager.GetString("UnsupportedNotification", resourceCulture);
            }
        }
    }
}
